export let ticketList = [
  {
    nombre: "Juan Pérez",
    idTicket: "001",
    email: "juan.perez@example.com",
    asunto: "Problema de acceso a la cuenta",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "María García",
    idTicket: "002",
    email: "maria.garcia@example.com",
    asunto: "Error en la facturación",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Carlos López",
    idTicket: "003",
    email: "carlos.lopez@example.com",
    asunto: "Solicitud de cambio de contraseña",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Ana Rodríguez",
    idTicket: "004",
    email: "ana.rodriguez@example.com",
    asunto: "Problema con la descarga de archivo",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Luis Fernández",
    idTicket: "005",
    email: "luis.fernandez@example.com",
    asunto: "Consulta sobre el producto",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Sofía Morales",
    idTicket: "006",
    email: "sofia.morales@example.com",
    asunto: "Error en la actualización de datos",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Ricardo Díaz",
    idTicket: "007",
    email: "ricardo.diaz@example.com",
    asunto: "Problema con el pago",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Laura Núñez",
    idTicket: "008",
    email: "laura.nunez@example.com",
    asunto: "Cambio en la suscripción",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Pedro Castillo",
    idTicket: "009",
    email: "pedro.castillo@example.com",
    asunto: "Consulta de facturación",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Carla Gómez",
    idTicket: "010",
    email: "carla.gomez@example.com",
    asunto: "Problema al iniciar sesión",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Jorge Vargas",
    idTicket: "011",
    email: "jorge.vargas@example.com",
    asunto: "Error en la visualización de productos",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Silvia Blanco",
    idTicket: "012",
    email: "silvia.blanco@example.com",
    asunto: "Asesoramiento sobre el producto",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Andrés Ruiz",
    idTicket: "013",
    email: "andres.ruiz@example.com",
    asunto: "Problema con el envío",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Daniela Silva",
    idTicket: "014",
    email: "daniela.silva@example.com",
    asunto: "Consulta sobre políticas de privacidad",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Mario Castro",
    idTicket: "015",
    email: "mario.castro@example.com",
    asunto: "Problema con la actualización de la cuenta",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Julia Fuentes",
    idTicket: "016",
    email: "julia.fuentes@example.com",
    asunto: "Cambio de información de pago",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Héctor Campos",
    idTicket: "017",
    email: "hector.campos@example.com",
    asunto: "Error en la configuración de notificaciones",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Elena Cabrera",
    idTicket: "018",
    email: "elena.cabrera@example.com",
    asunto: "Problema al registrarse",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Fernando Cruz",
    idTicket: "019",
    email: "fernando.cruz@example.com",
    asunto: "Consulta sobre la garantía",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Valeria Rojas",
    idTicket: "020",
    email: "valeria.rojas@example.com",
    asunto: "Problema con la descarga de documentos",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Roberto Mendoza",
    idTicket: "021",
    email: "roberto.mendoza@example.com",
    asunto: "Problema al hacer login",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Paola Salas",
    idTicket: "022",
    email: "paola.salas@example.com",
    asunto: "Error en la facturación",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Esteban Jiménez",
    idTicket: "023",
    email: "esteban.jimenez@example.com",
    asunto: "Solicitud de devolución",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Carolina Paredes",
    idTicket: "024",
    email: "carolina.paredes@example.com",
    asunto: "Cambio en los datos personales",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "David Ortega",
    idTicket: "025",
    email: "david.ortega@example.com",
    asunto: "Consulta sobre reembolso",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Santiago Ramírez",
    idTicket: "026",
    email: "santiago.ramirez@example.com",
    asunto: "Error en la aplicación móvil",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Gloria Martínez",
    idTicket: "027",
    email: "gloria.martinez@example.com",
    asunto: "Problema al realizar una compra",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Fabián Peña",
    idTicket: "028",
    email: "fabian.pena@example.com",
    asunto: "Solicitud de cambio de dirección",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Patricia Romero",
    idTicket: "029",
    email: "patricia.romero@example.com",
    asunto: "Consulta sobre promociones",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Felipe Vargas",
    idTicket: "030",
    email: "felipe.vargas@example.com",
    asunto: "Problema de acceso al sistema",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Alejandra Soto",
    idTicket: "031",
    email: "alejandra.soto@example.com",
    asunto: "Error en el envío de correos",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Gustavo León",
    idTicket: "032",
    email: "gustavo.leon@example.com",
    asunto: "Consulta sobre términos y condiciones",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Natalia Vega",
    idTicket: "033",
    email: "natalia.vega@example.com",
    asunto: "Error en la descarga del recibo",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Emilio Flores",
    idTicket: "034",
    email: "emilio.flores@example.com",
    asunto: "Problema con la autenticación",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Isabel Valenzuela",
    idTicket: "035",
    email: "isabel.valenzuela@example.com",
    asunto: "Consulta sobre compatibilidad de dispositivo",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Gabriel Montalvo",
    idTicket: "036",
    email: "gabriel.montalvo@example.com",
    asunto: "Error en el perfil de usuario",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Manuela Quintero",
    idTicket: "037",
    email: "manuela.quintero@example.com",
    asunto: "Solicitud de baja del servicio",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Cristian Márquez",
    idTicket: "038",
    email: "cristian.marquez@example.com",
    asunto: "Problema al validar identidad",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Pamela Santos",
    idTicket: "039",
    email: "pamela.santos@example.com",
    asunto: "Consulta sobre la política de uso",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Mauricio Torres",
    idTicket: "040",
    email: "mauricio.torres@example.com",
    asunto: "Problema con las notificaciones",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Lucía Herrera",
    idTicket: "041",
    email: "lucia.herrera@example.com",
    asunto: "Error en el historial de pedidos",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Alfredo Morales",
    idTicket: "042",
    email: "alfredo.morales@example.com",
    asunto: "Cambio en la configuración de cuenta",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Yolanda Soto",
    idTicket: "043",
    email: "yolanda.soto@example.com",
    asunto: "Problema con la carga de documentos",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Vicente Ponce",
    idTicket: "044",
    email: "vicente.ponce@example.com",
    asunto: "Error en la visualización de reportes",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Teresa Gutiérrez",
    idTicket: "045",
    email: "teresa.gutierrez@example.com",
    asunto: "Consulta sobre renovación de cuenta",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Marcos Benítez",
    idTicket: "046",
    email: "marcos.benitez@example.com",
    asunto: "Problema en el proceso de pago",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Florencia Muñoz",
    idTicket: "047",
    email: "florencia.munoz@example.com",
    asunto: "Consulta sobre la política de reembolso",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "Damián Herrera",
    idTicket: "048",
    email: "damian.herrera@example.com",
    asunto: "Error al actualizar el perfil",
    estado: "cerrado",
    resultado: "resuelto",
  },
  {
    nombre: "Antonia Torres",
    idTicket: "049",
    email: "antonia.torres@example.com",
    asunto: "Problema al crear la cuenta",
    estado: "abierto",
    resultado: "no resuelto",
  },
  {
    nombre: "José Molina",
    idTicket: "050",
    email: "jose.molina@example.com",
    asunto: "Consulta sobre tiempo de respuesta",
    estado: "cerrado",
    resultado: "resuelto",
  },
];
